### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by ljayvee** [blippy/neoleo#42]
[lucas@archlinux neoleo-9.0]$ env CPPFLAGS=-I/user/local/include LDFLAGS=-s ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
configure: checking if debugging required ... no
configure: checking if gprof profiling required ... no
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking for bison... bison -y
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating examples/Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating tests/out/Makefile
config.status: creating tests/verified/Makefile
config.status: executing depfiles commands

[lucas@archlinux neoleo-9.0]$ sudo make install
[sudo] password for lucas:
Making install in examples
make[1]: Entering directory '/home/lucas/aur/neohleo/neoleo-9.0/examples'
make[2]: Entering directory '/home/lucas/aur/neohleo/neoleo-9.0/examples'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/usr/local/share/neoleo/examples'
 /usr/bin/install -c -m 644 blank.oleo docs.oleo loop.oleo mysql.oleo nogood.oleo pivot.oleo plot.oleo shit.oleo test.oleo types.oleo xy.oleo q110399.csv formula.sylk oleo.pm6 create_koers.txt data.sql pivot.r '/usr/local/share/neoleo/examples'
make[2]: Leaving directory '/home/lucas/aur/neohleo/neoleo-9.0/examples'
make[1]: Leaving directory '/home/lucas/aur/neohleo/neoleo-9.0/examples'
Making install in src
make[1]: Entering directory '/home/lucas/aur/neohleo/neoleo-9.0/src'
make  install-am
make[2]: Entering directory '/home/lucas/aur/neohleo/neoleo-9.0/src'
g++ -DHAVE_CONFIG_H -I. -I..   -I/user/local/include -Werror -std=c++17 -Wno-write-strings -DDATADIR="\"/usr/local/share\""  -Wfatal-errors  -MT args.o -MD -MP -MF .deps/args.Tpo -c -o args.o args.cc
mv -f .deps/args.Tpo .deps/args.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/user/local/include -Werror -std=c++17 -Wno-write-strings -DDATADIR="\"/usr/local/share\""  -Wfatal-errors  -MT basic.o -MD -MP -MF .deps/basic.Tpo -c -o basic.o basic.cc
mv -f .deps/basic.Tpo .deps/basic.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/user/local/include -Werror -std=c++17 -Wno-write-strings -DDATADIR="\"/usr/local/share\""  -Wfatal-errors  -MT busi.o -MD -MP -MF .deps/busi.Tpo -c -o busi.o busi.cc
mv -f .deps/busi.Tpo .deps/busi.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/user/local/include -Werror -std=c++17 -Wno-write-strings -DDATADIR="\"/usr/local/share\""  -Wfatal-errors  -MT byte-compile.o -MD -MP -MF .deps/byte-compile.Tpo -c -o byte-compile.o byte-compile.cc
mv -f .deps/byte-compile.Tpo .deps/byte-compile.Po
g++ -DHAVE_CONFIG_H -I. -I..   -I/user/local/include -Werror -std=c++17 -Wno-write-strings -DDATADIR="\"/usr/local/share\""  -Wfatal-errors  -MT cell.o -MD -MP -MF .deps/cell.Tpo -c -o cell.o cell.cc
cell.cc: In member function ‘void cell::set_error(const ValErr&)’:
cell.cc:74:23: error: cannot convert ‘int’ to ‘value_t’ {aka ‘std::variant<double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, err_t, rng, bool_t, empty_t>’}
   74 |  set_value_2019(ve.num());
      |                 ~~~~~~^~
      |                       |
      |                       int
compilation terminated due to -Wfatal-errors.
make[2]: *** [Makefile:529: cell.o] Error 1
make[2]: Leaving directory '/home/lucas/aur/neohleo/neoleo-9.0/src'
make[1]: *** [Makefile:682: install] Error 2
make[1]: Leaving directory '/home/lucas/aur/neohleo/neoleo-9.0/src'
make: *** [Makefile:413: install-recursive] Error 1

**Comment by blippy** [comment]
Confirmed. Please standby for fix.

**Comment by blippy** [comment]
Should be fixed by https://github.com/blippy/neoleo/releases/tag/v10.0

Please confirm fix.

You should also be able to build it from the AUR: https://aur.archlinux.org/packages/neoleo/ which should be a little easier, assuming you have some AUR utils.

**Comment by ljayvee** [comment]
Yep works now thanks
