### ISSUE TITLE
Make error encountered

### ISSUE THREAD

**Issue by brucehohl** [blippy/neoleo#7]
When attempting to build 5.0.0 I encountered a make error on Linux Mint 18 per the attached.  I was able to build a previous version through commit 50e2a90.
[make-error.txt](https://github.com/blippy/neoleo/files/887769/make-error.txt)

**Comment by blippy** [comment]
Thanks for the error report. Please

`configure "CXXFLAGS= -std=gnu++11" `

then `make`. Tell me how you get on. I'm not sure how old the Mint compiler is; but it appears that it doesn't assume modern version of C++.

**Comment by blippy** [comment]
Also, can you please report what
`g++ --version`
returns. 

Slackware 14.2 uses g++ 5.3.0 (which supports -std=gnu++14), and I am wondering what Mint 18 version is.

**Comment by brucehohl** [comment]
Linux Mint 18 is a polished up version of Ubuntu 16.04 hence:
$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

This is the same OS install I used to successfully build an earlier version of neoleo per 1st comment.  I did get a different error when adding the flag suggested (same with alternate flag "CXXFLAGS=-std=c++0x")  "... fatal error: readline/readline.h: No such file or directory ..."  - see attached.
$ autoreconf -iv
$ ./configure "CXXFLAGS=-std=gnu++11"  [ $ ./configure "CXXFLAGS=-std=c++0x" ]
$ make
[build-error.txt](https://github.com/blippy/neoleo/files/888023/build-error.txt)

**Comment by blippy** [comment]
Aargh! Sorry about that. I should probably put in some kind of check for readline. I'm not sure what readline support there is in Mint (where's the Mint package list?), so try:
`sudo apt-get install libreadline-dev`
There shouldn't be any need to reconfigure after you do that. Just typing `make` should do it ... fingers crossed.

**Comment by brucehohl** [comment]
Mint ≈ Ubuntu ≈ Debian so packages can be listed with $ dpkg --list <package_name> 
I installed libreadline-dev and the build completed successfully - thanks for your help.

I did note that building --with-motif fails.  I don't really have any interest in a gui version and find motif to be ugly.  Do you see any future for the motif interface?  Also, can you could add some description and comments to the items listed in your release notes?  I see Tcl scripting support was added, then removed (in favor of atlast?), etc.  Additional description and comments on the reasoning for changes would be helpful to see how someone might utilize the changes.

**Comment by blippy** [comment]
I have recently removed all Motif support. It was too much of a maintenance burden. Plus, it relied on Xbae, which is a cell display. It is limited to 256 rows, so it's not very useful. 

X11 support is currently being deprecated, so that configuring '--with-x' is required. X11 will probably be removed in a subsequent version.

I have decided that it would be better to put all my eggs in one basket: ncurses. I am currently working on a simple menuing system for it. So my focus will be not so much in adding features, as in adding usability.

**Comment by brucehohl** [comment]
Just wanted to say that this issue is closed from my point of view.  Thanks for those comments.  I like the direction of focusing on ncurses and usability.  I added a test custom keybinding to my .oloerc and plan to explore that more for improved usability ... as time permits :)
